### ISSUE TITLE
to hide the start and end characters

### ISSUE THREAD

**Issue by wmhseir3** [gabdsg/flutter_decorated_text#1]
hi, is there any method to hide the start "{" and end "}" characters when with the following rule? thanks.

              DecoratorRule.between(
                start: "{",
                end: "}",
                style: TextStyle(
                  color: Colors.blue,
                ),
              ),

**Comment by gabdsg** [comment]
Not at the moment, but I can add it as a feature.

**Comment by gabdsg** [comment]
@wmhseir3 I just added this feature on version 1.0.6 **removeMatchingCharacters**
```
DecoratorRule.between(
   start: "{",
   end: "}",
   style: TextStyle(
      color: Colors.blue,
   ),
   removeMatchingCharacters: true
),

**Comment by wmhseir3** [comment]
you are more than just great. thanks. it does removeMatchingCharacters.
